apiVersion: v1
data:
  floating-ip: {{ default "" .Values.floatingip1 | b64enc | quote  }}
  hetzner-token: {{ default "" .Values.hetznertoken | b64enc | quote  }}
kind: Secret
metadata:
  name: hetzner-secret-failoverip-1
type: Opaque
